routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('productos', 'ProductoController');
Route::resource('categorias', 'CategoriaController');

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    /**
     * Get the comments for the blog post.
     */
    public function productos()
    {
        return $this->hasMany('App\Producto');
    }
}

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    /**
     * Get the post that owns the comment.
     */
    public function categoria()
    {
        return $this->belongsTo('App\Categoria');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categoria;
use App\Http\Requests;
use Exception;

class CategoriaController extends Controller
{
    private $path ='categoria';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Categoria::all();
        return view($this->path.'.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path.'.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*
         * Register producto.
         * */
        try{
            $categoria = new Categoria();
            $categoria->nombre           = $request->nombre;
            $categoria->save();
            return redirect()->route('categorias.index');
        }
        catch(Exception $e){
            return "Fatal error - ".$e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $categoria = Categoria::findOrFail($id);
            $categoria->delete();
            return redirect()->route('categorias.index');
        } catch (Exception $e){
            return "Fatal error - ".$e->getMessage();
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Producto;
use App\Http\Requests;
use Exception;

class ProductoController extends Controller
{
    private $path ='producto';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Producto::all();
        return view($this->path.'.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->path.'.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*
         * Register producto.
         * */
        try{
            $producto = new Producto();
            $producto->nombre           = $request->nombre;
            $producto->save();
            return redirect()->route('productos.index');
        }
        catch(Exception $e){
            return "Fatal error - ".$e->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $producto = Producto::findOrFail($id);
            $producto->delete();
            return redirect()->route('productos.index');
        } catch (Exception $e){
            return "Fatal error - ".$e->getMessage();
        }
    }
}

resources/views/categoria/create.blade.php
@extends('layouts.app')

@section('title', 'Registrar Categoria')

@section('content')
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Registro de Categorias</h3>
            <h4>
                <a href="{{ route('categorias.index') }}">
                    <span class="glyphicon glyphicon-menu-hamburger"></span>
                    Listar Productos
                </a>
            </h4>
        </div>
        <div class="panel-body">
            <form method="post" action="/categorias">
                @include('categoria.form')
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-floppy-disk"></span>
                    Registrar
                </button>
            </form>
        </div>
    </div>
@endsection

resources/views/categoria/form.blade.php
<input type="hidden" name="_token" value="{{ csrf_token() }}">

@if(isset($categorias))
    <div class="form-group">
        <label for="#">Nombre</label>
        <input type="text" name="nombre" class="form-control" placeholder="Nombre" value="{{ $categorias->nombre }}" required>
    </div>
@else
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label for="#">Nombre</label>
                <input type="text" name="nombre" class="form-control" placeholder="nombre" required>
            </div>
        </div>
    </div>
@endif

resources/views/categoria/index.blade.php
@extends('layouts.app')

@section('title', 'Listado Categorias')

@section('content')
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Listado de Categorias</h3>
            <h4>
                <a href="{{ route('categorias.create') }}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Registrar Categoria
                </a>
            </h4>
        </div>
            <div class="table-responsive">
                @if($data)
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $row)
                            <tr>
                                <td>{{ $row->nombre }}</td>
                                <td>
                                    <a class="glyphicon glyphicon-search tooltips" style="color: black;" href="#" title="ver" rel="tooltip"></a>
                                    <a class="glyphicon glyphicon-edit tooltips" style="color: black;" href="{{ route('productos.edit', $row->id) }}" title="editar" rel="tooltip"></a>
                                    <a class="glyphicon glyphicon-remove tooltips" href="#" onclick="document.getElementById('delete').submit()" style="color: black;" title="borrar" rel="tooltip"></a>
                                    <form action="{{ route('categorias.destroy', $row->id) }}" method="post" id="delete">
                                        <input name="_method" type="hidden" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" style="display: none;"></button>
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                        @endforeach
                    </table>
                @endif
            </div>
    </div>
@endsection

resources/views/child.blade.php
@extends('layouts.app')

@section('title', 'Page Title')

@section('sidebar')
    @parent

    <p>This is appended to the master sidebar.</p>
@endsection

@section('content')
    <p>This is my body content.</p>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>NCADMIN - @yield('title')</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

        <!-- Styles -->
        <style>
            html, body {
                background-color: #101010;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 7vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="top-center links">
                <a href="{{ url('/') }}">Inicio</a>
                <a href="{{ url('/productos') }}">Productos</a>
                <a href="{{ url('/categorias') }}">Categorias</a>
            </div>
        </div>

        <div class="container">
            @yield('content')
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    </body>
</html>

resources/views/producto/create.blade.php
@extends('layouts.app')

@section('title', 'Registrar Producto')

@section('content')
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Registro de Productos</h3>
            <h4>
                <a href="{{ route('productos.index') }}">
                    <span class="glyphicon glyphicon-menu-hamburger"></span>
                    Listar Productos
                </a>
            </h4>
        </div>
        <div class="panel-body">
            <form method="post" action="/productos">
                @include('producto.form')
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-floppy-disk"></span>
                    Registrar
                </button>
            </form>
        </div>
    </div>
@endsection

resources/views/producto/form.blade.php
<input type="hidden" name="_token" value="{{ csrf_token() }}">

@if(isset($producto))
    <div class="form-group">
        <label for="#">Nombre</label>
        <input type="text" name="nombre" class="form-control" placeholder="Nombre" value="{{ $producto->nombre }}" required>
    </div>
@else
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label for="#">Nombre</label>
                <input type="text" name="nombre" class="form-control" placeholder="nombre" required>
            </div>
        </div>
    </div>
@endif

resources/views/producto/index.blade.php
@extends('layouts.app')

@section('title', 'Listado Productos')

@section('content')
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Listado de Productos</h3>
            <h4>
                <a href="{{ route('productos.create') }}">
                    <span class="glyphicon glyphicon-plus"></span>
                    Registrar Producto
                </a>
            </h4>
        </div>
            <div class="table-responsive">
                @if($data)
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $row)
                            <tr>
                                <td>{{ $row->nombre }}</td>
                                <td>
                                    <a class="glyphicon glyphicon-search tooltips" style="color: black;" href="#" title="ver" rel="tooltip"></a>
                                    <a class="glyphicon glyphicon-edit tooltips" style="color: black;" href="{{ route('productos.edit', $row->id) }}" title="editar" rel="tooltip"></a>
                                    <a class="glyphicon glyphicon-remove tooltips" href="#" onclick="document.getElementById('delete').submit()" style="color: black;" title="borrar" rel="tooltip"></a>
                                    <form action="{{ route('productos.destroy', $row->id) }}" method="post" id="delete">
                                        <input name="_method" type="hidden" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" style="display: none;"></button>
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                        @endforeach
                    </table>
                @endif
            </div>
    </div>
@endsection